### PR TITLE
Switch to nan v2

### PR DESCRIPTION
**Pull request by jdesboeufs**
To bring compatibility with io.js v3 and node.js v4.

### CODE REVIEW

**Comment by jdesboeufs** [comment]
Reference to nodejs/node#2798!

**Comment by jdesboeufs** [comment]
Any problem?

**Comment by tmcw** [comment]
cc @mikemorris for the review

**Comment by mikemorris** [comment]
Changes look :+1: to me and the failed AppVeyor build looks like it's just from a random timeout.

**Comment by springmeyer** [comment]
1.x now depends on node-gdal rather than carrying the C++ from gdal internally. So, thank you for your contribution, however it is no longer needed.

**Pull request closed without merging**
